### ISSUE TITLE
SwitchToLastOpenedWindow works incorrectly

### ISSUE THREAD

**Issue by nkurt** [eger-geger/Selenium.HtmlElements.Net#11]
Sometimes SwitchToLastOpenedWindow stays on the same window. Seems like the reason to this could be that

> The order in which the window handles are returned is arbitrary
https://w3c.github.io/webdriver/#get-window-handles

So sometimes the last window handle in the list is actually the current window you are working with.

**Comment by eger-geger** [comment]
Fixed in 3.1.0
