### ISSUE TITLE
HtmlFrame elements are not accessible without frame CacheLookup

### ISSUE THREAD

**Issue by Bakanych** [eger-geger/Selenium.HtmlElements.Net#3]
Hi,
I found that issue trying to use HtmlFrame object without CacheLookup. For ex. if I use the following in PageAlpha class:

        [FindsBy(How = How.CssSelector, Using = "iframe")]
        public PageBeta BetaFrame { get; set; }

ShouldSwitchToFrameWhenWorkingWithIt test will be failed.

**Comment by eger-geger** [comment]
Thank you for submitting an issue. I'll try to fix it this weekends,

**Comment by eger-geger** [comment]
It should be fixed. [HtmlElements 2.0.3](https://www.nuget.org/packages/HtmlElements/2.0.3)

**Comment by Bakanych** [comment]
Just'v tested and it works well now. Thanks a lot!
