### ISSUE TITLE
Inject custom objects into PageObject

### ISSUE THREAD

**Issue by Bakanych** [eger-geger/Selenium.HtmlElements.Net#4]
Hi,
i continue to use this framework and i cannot find any options how to pass custom object into pageobject instance created by factory. It can be like this:
````
pageFactory.Create<MyPageObject>(webDriver, args)
````
Any other ideas?

**Comment by eger-geger** [comment]
There is no such method as of today. You could add one if you'd like. Alternatively you could create page object instance yourself and then call _Init_ method. 

```C#
public TPage CreatePageObject<TPage>(ISearchContext context, params object[] arguments) {
    var instance = Activator.CreateInstance(typeof(TPage), arguments);

    _pageObjectFactory.Init(instance, context);

    return instance;
}
```
